name: Linux

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  BUILD_TYPE: Release
  CH_SERVER_VERSION: 21.3.17.2
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        compiler: [clang-6, gcc-7, gcc-8, gcc-9]
        ssl: [ssl_ON, ssl_OFF]
        dependencies: [dependencies_SYSTEM, dependencies_BUILT_IN]
        include:
        - compiler: clang-6
          INSTALL: clang-6.0
          C_COMPILER: clang-6.0
          CXX_COMPILER: clang++-6.0

        - compiler: gcc-7
          INSTALL: gcc-7 g++-7
          C_COMPILER: gcc-7
          CXX_COMPILER: g++-7

        - compiler: gcc-8
          INSTALL: gcc-8 g++-8
          C_COMPILER: gcc-8
          CXX_COMPILER: g++-8

        - compiler: gcc-9
          INSTALL: gcc-9 g++-9
          C_COMPILER: gcc-9
          CXX_COMPILER: g++-9

        - ssl: ssl_ON
          INSTALL_SSL: libssl-dev
          OPENSSL_CMAKE_OPTION: -DWITH_OPENSSL=ON

        - ssl: ssl_OFF
          OPENSSL_CMAKE_OPTION: -DWITH_OPENSSL=OFF

        - dependencies: dependencies_SYSTEM
          DEPENDENCIES_CMAKE_OPTIONS: -DWITH_SYSTEM_ABSEIL=ON -DWITH_SYSTEM_LZ4=ON -DWITH_SYSTEM_CITYHASH=ON
          INSTALL_DEPENDENCIES: libabsl-dev liblz4-dev libcityhash-dev

        - dependencies: dependencies_BUILT_IN
          DEPENDENCIES_CMAKE_OPTIONS: -DWITH_SYSTEM_ABSEIL=OFF -DWITH_SYSTEM_LZ4=OFF -DWITH_SYSTEM_CITYHASH=OFF

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: sudo apt-get install -y cmake ${{ matrix.INSTALL }} ${{ matrix.INSTALL_SSL }} ${{ matrix.INSTALL_DEPENDENCIES }}

    - name: Configure CMake
      run: |
        cmake \
          -DCMAKE_C_COMPILER=${{ matrix.C_COMPILER}} \
          -DCMAKE_CXX_COMPILER=${{ matrix.CXX_COMPILER}} \
          -B ${{github.workspace}}/build \
          -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DBUILD_TESTS=ON \
          ${{ matrix.OPENSSL_CMAKE_OPTION}} \
          ${{ matrix.DEPENDENCIES_CMAKE_OPTIONS }}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} --target all

    - name: Start ClickHouse server
      run: |
        sudo apt-get install apt-transport-https ca-certificates dirmngr
        sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv E0C56BD4
        echo "deb https://repo.clickhouse.com/deb/stable/ main/" | sudo tee /etc/apt/sources.list.d/clickhouse.list
        sudo apt-get update
        sudo apt-get install -y \
            clickhouse-server=${{env.CH_SERVER_VERSION}} \
            clickhouse-client=${{env.CH_SERVER_VERSION}} \
            clickhouse-common-static=${{env.CH_SERVER_VERSION}}
        sudo service clickhouse-server start

    - name: Test
      working-directory: ${{github.workspace}}/build/ut
      run: ./clickhouse-cpp-ut
