name: macOS

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  BUILD_TYPE: Release
  CLICKHOUSE_USER: clickhouse_cpp_cicd
  CLICKHOUSE_PASSWORD: clickhouse_cpp_cicd

jobs:
  build:
    runs-on: macos-latest

    strategy:
      fail-fast: false
      matrix:
        build: [nossl, ssl]
        dependencies: [dependencies_SYSTEM, dependencies_BUILT_IN]
        include:
        - build: nossl
          openssl_cmake_option: -DWITH_OPENSSL=OFF

        - build: ssl
          openssl_cmake_option: -DWITH_OPENSSL=ON -DOPENSSL_ROOT_DIR=/usr/local/opt/openssl/
          openssl_install: openssl

        - dependencies: dependencies_SYSTEM
          dependencies_cmake_options: -DWITH_SYSTEM_ABSEIL=ON -DWITH_SYSTEM_LZ4=ON -DWITH_SYSTEM_CITYHASH=ON
          dependencies_install: abseil lz4 cityhash

        - dependencies: dependencies_BUILT_IN
          dependencies_cmake_options: -DWITH_SYSTEM_ABSEIL=OFF -DWITH_SYSTEM_LZ4=OFF -DWITH_SYSTEM_CITYHASH=OFF


    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: brew install cmake ${{matrix.openssl_install}} ${{matrix.dependencies_install}}

    - name: Configure CMake
      run: cmake \
              -B ${{github.workspace}}/build \
              -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} \
              -DBUILD_TESTS=ON \
              ${{matrix.openssl_cmake_option}} \
              ${{matrix.dependencies_cmake_options}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} --target all

    - name: Start tls offoader proxy
      # that mimics non-secure clickhouse running on localhost
      # by tunneling queries to remote tls server
      # (needed because we can't start real clickhouse instance on macOS)
      run: |
            wget https://github.com/filimonov/go-tlsoffloader/releases/download/v0.1.2/go-tlsoffloader_0.1.2_Darwin_x86_64.tar.gz
            tar -xvzf go-tlsoffloader_0.1.2_Darwin_x86_64.tar.gz
            ./go-tlsoffloader -l localhost:9000 -b github.demo.trial.altinity.cloud:9440 &

    - name: Test
      working-directory: ${{github.workspace}}/build/ut
      env:
        # It is impossible to start CH server in docker on macOS due to github actions limitations,
        # so limit tests to ones that do no require server interaction.
        GTEST_FILTER_ONLY_LOCAL: "-Client/*"
      run: ./clickhouse-cpp-ut
